### ISSUE TITLE
WG2闪退

### ISSUE THREAD

**Issue by Hasasiki** [yingDev/WGestures2-bugs#15]
wg2版本 2.3.2
Mac bigsur 11.1
wg2在后台一段时间后（几分钟）会自己退出

**Comment by yingDev** [comment]
聚焦搜索 Console.app 打开 > 崩溃报告, 里面有没有 WGestures 条目?

**Comment by Hasasiki** [comment]
未发现相关日志。
而且今天就没有发生这个问题。
也没有关机或重启过，就离谱。
