### ISSUE TITLE
购买之后才发现win还不支持

### ISSUE THREAD

**Issue by FantaZZ** [yingDev/WGestures2-bugs#22]
谢谢作者的作品，一直是WGestures的忠实用户，最近无意看2出来了，直接支付，然后下载，，，
尴尬了，发现不支持win，这，，，

**Comment by FantaZZ** [comment]
估计win要多久出来呢

**Comment by FantaZZ** [comment]
建议在购买页面，先提示下，win版本暂时还没有出来

**Comment by 527570755** [comment]
我都从去年等到现在了，打算内测版能用上也成，发现作者并没有回复/(ㄒoㄒ)/~~

**Comment by Hisen5** [comment]
我也是一直在等win版本，太期待了

**Comment by HHHHhgqcdxhg** [comment]
同支付了发现不支持win, 有资格催更了嗷!  

那个, 小应, 你那个桌面鼠标手势的项目, 加把劲好好干哈

**Comment by yingDev** [comment]
已经发布了
