### ISSUE TITLE
MAC 版 WG2 建议能有配置导入与导出的功能

### ISSUE THREAD

**Issue by ioiioo** [yingDev/WGestures2-bugs#3]
手头上 macOS 设备有好几台,当新在新的设备上面使用时,为自己配置好的设置又需要重新对照着配置一次;有些重复劳动繁琐.

**Comment by yingDev** [comment]
考虑 2.2 实现

**Comment by kchen0x** [comment]
配置同步岂不更好？
或者配置同步文件夹，用户自行使用 iCloud/Dropbox 进行同步。
