### ISSUE TITLE
4个问题

### ISSUE THREAD

**Issue by zhj9709** [yingDev/WGestures2-bugs#32]
Windows11

1. 我添加了一个分组，分组重命名后，关闭窗口重新打开软件后，名字又变成group 0
2. 希望软件不要设置成始终置顶，截图时都不方便，比如我用snipaste想截WGestures2的部分界面时，截不了
3. 希望手势名称可以关闭已执行后显示的内容，不然手势画完了，手势名称还没消失，看着有点难受
4. 当使用浏览器时，最大化，光标移动到最左边或最右边滚动时，特别慢，关闭WGestures2后恢复正常

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/135797411-d264665c-fcc4-4e9f-8f5a-70dc0d968d4e.png)

**Comment by FantaZZ** [comment]
添加了一个分组，分组重命名后，关闭窗口重新打开软件后，名字又变成group 0
+1

**Comment by yingDev** [comment]
1, 2, 3 ：2.3.6 已解决。

4：我的电脑上暂时没有重现

**Comment by zhj9709** [comment]
> 1, 2, 3 ：2.3.6 已解决。
> 
> 4：我的电脑上暂时没有重现

4就是 一般情况下，鼠标滚动转动一下，会滚动多次（关闭平滑滚动时比较明显），但光标移动到最左边跟最右边滚动时，只会滚一次。我换台电脑再试试。

**Comment by zhj9709** [comment]
https://github.com/zhj9709/issues/blob/master/WGestures2/32/bandicam%202021-10-05%2009-43-57-359.mp4?raw=true
我录了一个视频，视频中退出WGesture2前后鼠标滚动都是一样的，但退出前只滚动一次，退出后就正常。

**Comment by zhj9709** [comment]
刚在我的台式机上测试了，一样的问题，而且发个一个新问题。我是远程连接我台式机的，发现手势不能用，这需要等我用台式机时才能确定是不是远程的问题。

**Comment by zhj9709** [comment]
#36
