### ISSUE TITLE
鼠标右键 + 滚轮切换标签页无法连续切换

### ISSUE THREAD

**Issue by kalarita** [yingDev/WGestures2-bugs#41]
版本: windows 2.4.2
如题, 在wgestures 1 中是可以通过鼠标滚轮和右键连续切换标签页的, 但是到了2之后就不行了, 只能切换一个松开右键再来一次, 是否可以考虑再重写下这个功能呢🙈

**Comment by yingDev** [comment]
请更新到 2.4.3 看问题是否还存在?

**Comment by ClixTW** [comment]
沒問題了👍

**Comment by kalarita** [comment]
抱歉, 回复晚了, 现在是2.4.4, 已经没问题了👍
